# configs/config.yaml
model:
  name: "resnet50"
  num_classes: 2  # Updated to match our classes
  pretrained: true
  save_dir: "models/saved_models"

data:
  input_size: 224
  batch_size: 32
  train_path: "data/processed/train"
  val_path: "data/processed/val"
  test_path: "data/processed/test"

training:
  learning_rate: 0.001
  num_epochs: 20
  device: "cpu"  # Change to "cuda" if you have GPU